export const Chats = [
    {
        id: 1,
        name: 'Bukayo Saka',
        lastMessage: 'That is what thought too',
        lastMessageTime: '1:22 PM',
        avatar: 'https://i.pravatar.cc/150?img=1',
        isOnline: true,
        isTyping: false,
        messages: [
            {
                id: 1,
                sender: 'Bukayo Saka',
                message: 'That is what thought also',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Funmi Hart',
                message: 'What about us',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 3,
                sender: 'Bukayo Saka',
                message: 'What about all the things we have been through',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Funmi Hart',
                message: 'What about trust',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Bukayo Saka',
                message: 'You know i never meant to hurt you',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Funmi Hart',
                message: 'Living in my own world',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Bukayo Saka',
                message: 'I never believed in what i couldnt see',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Funmi Hart',
                message: 'This could be the start of something new',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Bukayo Saka',
                message: 'That is what thought also',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Funmi Hart',
                message: 'That is what thought also',
                timestamp: '13:22 PM',
                isRead: true,
            },
            {
                id: 2,
                sender: 'Bukayo Saka',
                message: 'That is what thought also',
                timestamp: '13:22 PM',
                isRead: true,
            },

        ]
    },
    {
        id: 2,
        name: 'Jurrien Timber',
        lastMessage: 'That is what thought also',
        lastMessageTime: '13:22 PM',
        avatar: 'https://i.pravatar.cc/150?img=1',
        isOnline: true,
        isTyping: false,
    },
    {
        id: 3,
        name: 'Gabriel Martinelli',
        lastMessage: 'That is what thought also',
        lastMessageTime: '13:22 PM',
        avatar: 'https://i.pravatar.cc/150?img=1',
        isOnline: true,
        isTyping: false,
    },
    {
        id: 4,
        name: 'Martin Odegaard',
        lastMessage: 'That is what thought also',
        lastMessageTime: '13:22 PM',
        avatar: 'https://i.pravatar.cc/150?img=1',
        isOnline: true,
        isTyping: false,
    },
    {
        id: 5,
        name: 'Gabriel Jesus',
        lastMessage: 'That is what thought also',
        lastMessageTime: '13:22 PM',
        avatar: 'https://i.pravatar.cc/150?img=1',
        isOnline: true,
        isTyping: false,
    },
    {
        id: 6,
        name: 'William Saliba',
        lastMessage: 'That is what thought also',
        lastMessageTime: '13:22 PM',
        avatar: 'https://i.pravatar.cc/150?img=2',
        isOnline: true,
        isTyping: false,
    },
    {
        id: 7,
        name: 'Gabriel Martinelli',
        lastMessage: 'That is what thought also',
        lastMessageTime: '13:22 PM',
        avatar: 'https://i.pravatar.cc/150?img=3',
        isOnline: true,
        isTyping: false,
    },
    {
        id: 8,
        name: 'Martin Odegaard',
        lastMessage: 'That is what thought also',
        lastMessageTime: '13:22 PM',
        avatar: 'https://i.pravatar.cc/150?img=4',
        isOnline: true,
        isTyping: false,
    },
];
